sudo: required
services:
  - docker

before_install:
  - docker build -t tomotoyinbo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tomotoyinbo/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-React"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-450089999649"
  bucket_path: "Docker-React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
