sudo: required
services:
  - docker

before_install:
  - docker build -t tomotoyinbo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tomotoyinbo/docker-react npm run test

language: generic